global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Reflection.Emit;
global using System.Runtime.CompilerServices;
global using BepInEx;
global using BepInEx.Configuration;
global using BepInEx.Logging;
global using BepInEx.Bootstrap;
global using HarmonyLib;
global using JetBrains.Annotations;
global using ServerSync;
global using Steamworks;
global using TMPro;
global using UnityEngine;
global using UnityEngine.Rendering;
global using UnityEngine.UI;
global using System.Threading.Tasks;
global using Random = UnityEngine.Random;
global using Object = UnityEngine.Object;
global using System.Runtime.InteropServices;
global using Steamworks;